---
title: "Space conjunction analysis in support of USSPACECOM"
output: flexdashboard::flex_dashboard
runtime: shiny
---




```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(cowplot)
library(tidyverse)
library(flexdashboard)


conf_matrix_plot<-function(df = data_from_function, i){
mat <-matrix(df[i,2:5],2,2) %>% data.frame() %>%  rename("Benign"= X1, "Malicious" = X2)

data <-matrix(rep(0,12),4,3) %>% data.frame()%>%  rename("Prediction"= X1, "Reference" = X2, "Freq" = X3)
data$Prediction <- c("Malicious", "Benign", "Malicious","Benign")
#data$Prediction <- c("Benign", "Malicious", "Benign","Malicious")
data$Reference <- c("Malicious", "Malicious", "Benign", "Benign")
data$discript <-c("Correctly Predicted Malicious","Falsely Predicted Benign", "Falsely Predicted Malicious" ,"Correctly Predicted Benign")

#data$Reference <- c("Benign", "Benign", "Malicious", "Malicious")
data[1,3] <- mat[2,2]
data[3,3] <- mat[1,2]
data[2,3] <- mat[2,1]
data[4,3] <- mat[1,1]
data <-data %>% 
  mutate(Prediction = factor(Prediction, levels = c( "Benign","Malicious")),  #c( "Benign","Malicious")
                        Reference= factor(Reference, levels = c("Malicious", "Benign")))  # c("Malicious", "Benign")

num_obs <- sum(data$Freq)
num_ben <- sum(data[3,3]+ data[4,3])
num_mal <- sum(data[1,3] + data[2,3])

data <- data  %>%group_by(Reference) %>% 
  mutate(
    total = sum(Freq),
    frac_fill = if_else(Prediction == Reference, Freq / total, 0),
    frac = Freq / num_obs) %>% 
  ungroup() %>% 
  mutate(dist = ifelse(Reference == "Malicious", Freq/num_mal, Freq/num_ben )) 


  ggplot(data,aes(Prediction,Reference,fill = frac)) +
  geom_tile() +
  scale_fill_gradient(low = "#FFFFFF", high = "#0d4077",guide = FALSE) +
  scale_x_discrete(position = "top") +
  geom_text(aes(color = frac>0.1,label = str_c(discript,"\n",comma(Freq),"\n ", round(frac * 100,2), "% of all Observations \n", round(dist *100,2), "% of True ", Reference  )), size = 6)+
  scale_color_manual(values=c("#000000", "#FFFFFF"),guide = FALSE)+
  geom_tile(color = "black", fill = "black", alpha = 0)+
  theme_cowplot()+
    theme(axis.text=element_text(size=16),
          axis.title=element_text(size=16,face="bold"))
}
```

Column {.sidebar} {data-width=250}
-----------------------------------------------------------------------

Space conjunction analysis in support of USSPACECOM. Choose the selected parameters.

```{r}
# Number of Fragments
selectInput("NumFrags", label = "Number of fragments:",
            choices = c(1, 10, 100, 1000 ,10000), selected = 100)

# Days to TCA 
sliderInput("DaysTCA", label = "Days to TCA",
            min = 1, max = 10, value = 1, step = 1)

#threshold_Pc

sliderInput("PcThresh", label = "Pc Threshold",
            min = 1e-10, max = 1e-2,, value = 1e-5, step =1e-4)

textInput("inputA", "Concern Category A", 1e-3)
textInput("inputB", "Concern Category B", 1e-4)
textInput("inputC", "Concern Category C", 1e-5)



# source("./scripts/debrisConcernFunction.R")
# 
# debrisConcern(Pc_concern=c(inputA,inputB,inputC),
#                           days_to_TCA=DaysTCA,
#                           threshold_Pc=PcThresh,
#                           number_of_fragments=NumFrags,
#                           verbose=FALSE)

# This datatframe needs be an output of debrisConcern just dummy data at this time
data_from_function <- data.frame(
  name = c("Cat_A", "Cat_B", "Cat_C"),
  true_neg = c(5005,4242,14214),
  false_neg = c(4214,32542,3),
  false_pos = c(3253,253,32523),
  true_pos = c(1,646,6346))

```

Column
-----------------------------------------------------------------------
### Concern Category A 

```{r}
renderPlot({
conf_matrix_plot(data_from_function, 1)})

```
    
### Concern Category B 

```{r}
renderPlot({
conf_matrix_plot(data_from_function, 2)})
```

### Concern Category C 

```{r}
renderPlot({
conf_matrix_plot(data_from_function, 3)})
```