---
title: "Space conjunction analysis in support of USSPACECOM"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---




```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(cowplot)
library(tidyverse)
library(flexdashboard)
library(scales)
library(data.table)
library(shiny)
# # Read in required data

load("concernData.RData")
#
# Read in debrisCounfuction function
source("debrisConfusion.R")


conf_matrix_plot<-function(df = data_from_function, i){

  

mat <-matrix(df[i,2:5],2,2) %>% data.frame() %>%  rename("No Collision"= X1, "Collision" = X2)

data <-matrix(rep(0,12),4,3) %>% data.frame()%>%  rename("Warning"= X1, "Reference" = X2, "Freq" = X3)

data$Warning <- c("Collision", "No Collision", "Collision","No Collision")
#data$Warning <- c("No Collision", "Collision", "No Collision","Collision")
data$Reference <- c("Collision", "Collision", "No Collision", "No Collision")
data$discript <-c("Warning given and collision","No warning and collision", "Warning given and no collision" ,"No warning and no collision")


#data$Reference <- c("No Collision", "No Collision", "Collision", "Collision")
data[1,3] <- mat[2,2]
data[3,3] <- mat[1,2]
data[2,3] <- mat[2,1]
data[4,3] <- mat[1,1]
data <-data %>% 
  mutate(Warning = factor(Warning, levels = c( "No Collision","Collision")),  
                        Reference= factor(Reference, levels = c("Collision", "No Collision"))) 

num_obs <- sum(data$Freq)
num_ben <- sum(data[3,3]+ data[4,3])
num_mal <- sum(data[1,3] + data[2,3])

data <- data  %>%group_by(Reference) %>% 
  mutate(
    total = sum(Freq),
    frac_fill = if_else(Warning == Reference, Freq / total, 0),
    frac = Freq / num_obs) %>% 
  ungroup() %>% 
  mutate(dist = ifelse(Reference == "Collision", Freq/num_mal, Freq/num_ben )) 


  ggplot(data,aes(Warning,Reference,fill = frac)) +
  geom_tile() +
  scale_fill_gradient(low = "#FFFFFF", high = "#0d4077",guide = FALSE) +
  scale_x_discrete(position = "top") +
  geom_text(aes(color = frac>0.1,label = str_c(discript,"\n",comma(as.integer(Freq)),"\n ", round(frac * 100,2), "% of all Observations \n", round(dist *100,2), "% of True ", Reference  )), size = 6)+
  scale_color_manual(values=c("#000000", "#FFFFFF"),guide = FALSE)+
  geom_tile(color = "black", fill = "black", alpha = 0)+
  theme_cowplot()+
    theme(axis.text=element_text(size=16),
          axis.title=element_text(size=16,face="bold"))
}
```

Confusion Matrix  {data-navmenu="More Analysis"}
===================================== 

Column {.sidebar} 
-----------------------------------------------------------------------

Space conjunction analysis in support of USSPACECOM. Choose the selected parameters.

```{r}

# Number of Fragments
selectInput("NumFrags", label = "Number of fragments:",
            choices = c("PcBest", "PcFrag10", "PcFrag100", "PcFrag1000", "PcFrag10000"), selected = "PcBest")

# Days to TCA 
sliderInput("DaysTCA", label = "Days to TCA",
            min = 1, max = 8, value = 5, step = 1)

#threshold_Pc

sliderInput("PcWarn", label = "Pc Warn",
            min = 2.06e-9, max = 1e-1, value = 2.06e-9, step =1e-4)

textInput("inputA", "Concern Category A", 1e-3)
textInput("inputB", "Concern Category B", 1e-4)
textInput("inputC", "Concern Category C", 1e-5)

actionButton("MakeUpdates", "Update")
list_of_df = list()
make_data <- function(){

  index = 0
  for( i in c(input$inputA, input$inputB, input$inputC)){
    i <- as.numeric(i)
 
  Temp_df <- debrisConfusion(concernData_at_TOI=concernSummary_at_TOI,
                          concernData=concernSummary,
                          Pc_concern=i,
                          days_to_TCA=input$DaysTCA,
                          Pc_warn=input$PcWarn,
                          frag_number_Pc=input$NumFrags,
                          verbose=FALSE,
                          rate = FALSE)
 
  Temp_df <- Temp_df %>% 
    pivot_wider(names_from = `Type`, values_from = Count)
  
  names(Temp_df)<-  c("name", "false_neg", "false_pos","true_pos" ,"true_neg")
  
  Temp_df <- Temp_df %>% select(name, true_neg,false_neg ,false_pos ,true_pos )
  
  index = index + 1
  list_of_df[[index]] <- Temp_df
  }


  return(list_of_df)}


react <- eventReactive(input$MakeUpdates, {make_data()})


# This datatframe needs be an output of debrisConcern just dummy data at this time
# df <- data.frame(
#   name = c("Cat_A", "Cat_B", "Cat_C"),
#   true_neg = c(5005,4242,14214),
#   false_neg = c(4214,32542,3),
#   false_pos = c(3253,253,32523),
#   true_pos = c(1,646,6346))

```



Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Concern Category A 


```{r}
renderPlot({
  dfA <- react()[[1]]
conf_matrix_plot(dfA, 1)})

```
    
### Chart B 

```{r}

```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Concern Category B 

```{r}
renderPlot({
  dfB <- react()[[2]]
conf_matrix_plot(dfB, 1)})
```

### DFD

```{r}

```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Concern Category C 

```{r}
renderPlot({
   dfC <- react()[[3]]

conf_matrix_plot(dfC, 1)})

```

### Blahd 

```{r}

```


 New Page {data-navmenu="More Analysis"}
=====================================



 Yet another new Page {data-navmenu="More Analysis"}
=====================================